from django.db import migrations, models


def _ensure_dealership_schema(apps, schema_editor):
    """
    Sync database with Dealership model:
    - If the table is missing (fresh DB), create it.
    - If the table exists from an older schema, add new columns only.
    """
    connection = schema_editor.connection
    table = "Dashboard_dealership"

    def _table_exists():
        with connection.cursor() as cursor:
            if connection.vendor == "sqlite":
                cursor.execute(
                    "SELECT 1 FROM sqlite_master WHERE type='table' AND name=%s",
                    [table],
                )
                return cursor.fetchone() is not None
            return table in connection.introspection.table_names()

    def _column_names():
        with connection.cursor() as cursor:
            if connection.vendor == "sqlite":
                cursor.execute(f'PRAGMA table_info("{table}")')
                return {row[1] for row in cursor.fetchall()}
            cursor.execute(
                """
                SELECT column_name FROM information_schema.columns
                WHERE table_name = %s
                """,
                [table],
            )
            return {row[0] for row in cursor.fetchall()}

    if not _table_exists():
        if connection.vendor == "sqlite":
            schema_editor.execute(
                f"""
                CREATE TABLE "{table}" (
                    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    "name" varchar(200) NOT NULL,
                    "badge_css_class" varchar(80) NOT NULL DEFAULT 'bg-dark',
                    "is_default_home" integer NOT NULL DEFAULT 0
                )
                """
            )
        else:
            schema_editor.execute(
                f"""
                CREATE TABLE "{table}" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "name" varchar(200) NOT NULL,
                    "badge_css_class" varchar(80) NOT NULL DEFAULT 'bg-dark',
                    "is_default_home" boolean NOT NULL DEFAULT false
                )
                """
            )
        return

    cols = _column_names()
    if "badge_css_class" not in cols:
        if connection.vendor == "sqlite":
            schema_editor.execute(
                f'ALTER TABLE "{table}" ADD COLUMN "badge_css_class" varchar(80) NOT NULL DEFAULT \'bg-dark\''
            )
        else:
            schema_editor.execute(
                f'ALTER TABLE "{table}" ADD COLUMN "badge_css_class" varchar(80) NOT NULL DEFAULT \'bg-dark\''
            )
    if "is_default_home" not in cols:
        if connection.vendor == "sqlite":
            schema_editor.execute(
                f'ALTER TABLE "{table}" ADD COLUMN "is_default_home" integer NOT NULL DEFAULT 0'
            )
        else:
            schema_editor.execute(
                f'ALTER TABLE "{table}" ADD COLUMN "is_default_home" boolean NOT NULL DEFAULT false'
            )


def _reverse_noop(apps, schema_editor):
    pass


def seed_c3_toronto(apps, schema_editor):
    Dealership = apps.get_model("Dashboard", "Dealership")
    Dealership.objects.filter(is_default_home=True).update(is_default_home=False)
    d, _ = Dealership.objects.get_or_create(
        name="C3 Toronto",
        defaults={
            "badge_css_class": "ns-badge-c3-toronto",
            "is_default_home": True,
        },
    )
    if d.badge_css_class != "ns-badge-c3-toronto" or not d.is_default_home:
        d.badge_css_class = "ns-badge-c3-toronto"
        d.is_default_home = True
        d.save(update_fields=["badge_css_class", "is_default_home"])


def reverse_seed(apps, schema_editor):
    Dealership = apps.get_model("Dashboard", "Dealership")
    Dealership.objects.filter(name="C3 Toronto").update(
        badge_css_class="bg-dark",
        is_default_home=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0008_entry_documents"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Dealership",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=200)),
                        (
                            "badge_css_class",
                            models.CharField(
                                default="bg-dark",
                                help_text="Bootstrap/extra CSS classes for this dealership's badge (navbar, user list).",
                                max_length=80,
                            ),
                        ),
                        (
                            "is_default_home",
                            models.BooleanField(
                                default=False,
                                help_text="If True, new user group edits default to this dealership when none is set.",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["name"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(_ensure_dealership_schema, _reverse_noop),
            ],
        ),
        migrations.RunPython(seed_c3_toronto, reverse_seed),
    ]
