# Generated by Django 6.0.4 on 2026-04-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0020_claim_link_dailysale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(max_length=200)),
                ("vin", models.CharField(help_text="Vehicle identification number", max_length=17)),
                ("inspection_date", models.DateField()),
                ("odometer", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "installer_name",
                    models.CharField(
                        blank=True,
                        help_text="Installer or employee who performed the inspection.",
                        max_length=200,
                    ),
                ),
                ("passed", models.BooleanField(help_text="True = pass, False = fail")),
                ("notes", models.TextField(blank=True)),
                ("issue_damage", models.BooleanField(default=False)),
                ("issue_incomplete", models.BooleanField(default=False)),
                ("issue_warranty", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_sale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a recorded sale (order).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="Dashboard.dailysale",
                    ),
                ),
                ("dealership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inspections", to="Dashboard.dealership")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inspections", to="Dashboard.salesproduct")),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InspectionPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="inspection_photos/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="Dashboard.inspection")),
            ],
            options={
                "ordering": ["uploaded_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["vin"], name="Dashboard_i_vin_562318_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["dealership", "-inspection_date"], name="Dashboard_i_dealers_674f5c_idx"),
        ),
    ]
